language: java
jdk:
- openjdk8

addons:   
  sonarcloud:
    organization: VincenzoVisconti16
    token:
      secure: 5dd2de10f0a9b1d94dc8709bddeaf14d984d71d8
      
script: 
- ant build 
- sonar-scanner

